### ISSUE TITLE
parameters setting

### ISSUE THREAD

**Issue by ZianFang** [b2jia/jie#3]
Hi, Jia!
First I want to thank you for developing such a great tool to analyze seqFISH data! It is such a clever method and optimize the original datasets. 
And when I was walking thru the notebook tutorial, I encounter some confusions : 	
1. The dummy localization error added to the observed xyz is always set to 1 no matter what the unit of the xyz (e.g. um or mm) right? 	2. The parameters in pickle file for aligner.find_all_chr() can be directly used for the same type of cell and resolution? (e.g. mesc_2022_params_25kb_hic.pkl) Will I have to change some of the parameters due to the change of resolution or coverage or cell number or bead number? 

 Best wishes!

**Comment by b2jia** [comment]
Hi Zian,

Thanks for your feedback! The localization error can be derived through Gaussian fitting of punctas in raw images. For the sake of the tutorial/analaysis of seqFISH data (for which raw images aren’t available), I used a dummy error. Let me know if that helps clarify.

Bojing

**Comment by ZianFang** [comment]
Thanks! that helps me understand this localization error.
And could you please help me with this "2. The parameters in pickle file for aligner.find_all_chr() can be directly used for the same type of cell and resolution? (e.g. mesc_2022_params_25kb_hic.pkl) Will I have to change some of the parameters due to the change of resolution or coverage or cell number or bead number?" , thank you very much!!!

**Comment by b2jia** [comment]
Hi Zian,

Changing the parameters sounds reasonable, especially if you are working at a different genome scale (kb, Mb) and different model organism. You can refer to our supplemental section in our NBT paper for an idea how to tune this distance parameter.

Best,
Bojing

**Comment by ZianFang** [comment]
Hi Bojing,
Thank you for your explanation for my confusions! Now I have a clearer understanding of your program.
Now I have another tiny question:
The unit of the coordinate xyz can be presented as voxels and um (provided by original seqFISH datasets), and the nm_per_bp as well as positional uncertainties(50nm as introduced in NBT article) are using nanometer. Are the unit of these parameters going to be unified as nm and then run the aligner.find_all_chr() function? I have tried to convert all data related to distance to nanometers(xyz nm and set localization error as 50), but the output of all cells are empty. I don't know if it's due to the unit issue above. Could you please help me with this? Thank you very much!!!! 
Best wishes,
Zian

**Comment by b2jia** [comment]
Hi Zian,

The seqFISH data should be in units of voxels, wherein each voxels is around ~100 nm in xy. For a localization error of 50 nm I would use 0.5.

Bojing

**Comment by ZianFang** [comment]
Hi Bojing,
Thank you for your instruction on the units of the data! After adjusting the units, i still got many cells empty in the output of aligner.find_all_chr(). I wonder if its because those cells have low coverage of imaged beads? I tried for 100 cells and basically 90% are empty. I am using the data of 2023 biorxiv LongCai "High-resolution spatial multi-omics reveals cell-type specific nuclear compartments" mESC dataset. Sorry for bothering you! Thank u!!!
Yours,
zian

**Comment by b2jia** [comment]
Hi Zian,

You'll notice a few things about the 2023 biorxiv paper. (1) The genomic resolution is fine (25 kb), spanning the entire mouse genome (2) the data is very sparse, with ~10% detection efficiency. 

One key parameter is allowing the aligner to "skip" unseen or dropout spots, but there is an upper bound for how many the aligner is able to skip before terminating. Most likely reason you aren't getting any traces is because the data is so sparse. You can try playing with the skip parameters instead. To get an intuition for how the algorithm works, I refer you to the introductory jupyter notebook in this repo.

Hope this helps.
